apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: config-data
        configMap:
          name: message
          items:
          - key: "information.txt"
            path: "information.txt"
      - name: shared-data
        persistentVolumeClaim:
          claimName: data-claim
      containers:
        - name: log-writer
          image: log-writer
          imagePullPolicy: IfNotPresent
          volumeMounts: 
          - name: shared-data
            mountPath: /usr/src/app/files
        - name: log-reader
          #image: europe-north1-docker.pkg.dev/dwk-gke-502612/dwk-repository/log-reader:v1
          image: log-reader
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts: 
            - name: config-data
              mountPath: /usr/src/app/config
              readOnly: true
            - name: shared-data
              mountPath: /usr/src/app/files
          env:
            - name: message
              valueFrom:
                configMapKeyRef:
                  name: message
                  key: MESSAGE
