apiVersion: v1
kind: ConfigMap

metadata:
  namespace: project
  name: todo-db-config

data:
  POSTGRES_HOST: todo-postgres-svc
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: example-password
  POSTGRES_DB: todo_database