apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: project
  name: todo-generator

spec: 
  schedule: "0 * * * *"

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: todo-generator
              imagePullPolicy: Never

          
          restartPolicy: Never