apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: broadcaster-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: PROJECT/BROADCASTER
          imagePullPolicy: IfNotPresent

          env:
            - name: NATS_URL
              value: nats://my-nats.nats.svc.cluster.local:4222
            - name: WEBHOOK_URL
              value: "https://webhook.site/11b60a99-5543-4096-80c8-b71d5e48b6d9"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"