apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/config.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/todo-backend-deployment.yaml
  - manifests/todo-backend-service.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/generator-cronjob.yaml
  - manifests/backup-cronjob.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml

images:
  - name: PROJECT/TODO-APP
    newName: todo-app
    newTag: latest

  - name: PROJECT/TODO-BACKEND
    newName: todo-backend
    newTag: latest

  - name: PROJECT/TODO-GENERATOR
    newName: todo-generator
    newTag: latest