apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/config.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/todo-backend-deployment.yaml
  - manifests/todo-backend-service.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/generator-cronjob.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml

images:
  - name: PROJECT/TODO-APP
    newName: europe-north1-docker.pkg.dev/dwk-gke-502612/dwk-repository/todo-app
    newTag: v1

  - name: PROJECT/TODO-BACKEND
    newName: europe-north1-docker.pkg.dev/dwk-gke-502612/dwk-repository/todo-backend
    newTag: v1

  - name: PROJECT/TODO-GENERATOR
    newName: europe-north1-docker.pkg.dev/dwk-gke-502612/dwk-repository/todo-generator
    newTag: v1