apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: todo-data-claim
      containers:
        - name: todo-backend
          image: todo-backend
          imagePullPolicy: Never

          env:
            - name: PORT
              value: "3000"
          volumeMounts: 
            - name: data
              mountPath: /usr/src/app/files



